csui.define({
  toolbarButtonTitle: 'Sign',
  dialogTitle: 'Sign in External Portal',
  submitLabel: 'Create',
  submitSignLabel: 'Sign',
  docListHeader: 'Selected Documents',
  addNewVersion: 'Add version',
  createNew: 'Create new document',
  categoriesLabel: 'Categories',
  categoryPlaceholder: 'Category name',
  containerName: 'Container name',
  containerNamePlaceholder: 'Container name',
  personCode: 'Person code',
  mobileNumbner: 'Mobile',
  conCreated: 'Container created. Signing in progress...',
  signFinish: 'Container signed successfully.',
  conError: 'Error. Please try again.',
  msgPIN2Question: 'Status: signing started. Enter PIN2. Verification code: ',
  msgContainerSignedDownload: 'Container signed. Container link: ',
  msgContainerCreatedDownload: 'Container created. Container link: ',
  download: 'download',
  msgErrorTryAgain: 'Status: error. Please try again.'
});
