/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */

define({
  facetsTitle: 'Refine by',
  facetsRegionAria: 'Refinement options',
  facetTitleAria: 'Refine by {0}',
  searchIconTooltip: 'Search by {0}',
  filterTitle: '{0} ({1})',
  filterTitleAria: 'Filter {0} with {1} items',
  filterTitleAriaNoDisplayCount: 'Filter {0}',
  filterCheckboxAria: 'Filter {0} with {1} items',
  filterCheckboxAriaNoDisplayCount: 'Filter {0}',
  searchClearIconTooltip: 'Clear all',
  emptyFacetMessage: 'No filters available.',
  emptyFilteredFacetMessage: 'No more filters available.',
  loadingFacetMessage: 'Loading filters...',
  failedFacetMessage: 'Loading filters failed.',
  noFiles: 'No drop files were provided.',
  addTypeDenied: 'Cannot add documents to {0}.',
  showMore: 'Show more',
  showMoreAria: 'Show more filters',
  showLess: 'Show less',
  showLessAria: 'Show less filters',
  apply: 'Apply',
  applyFiltersAria: 'Apply selected filters',
  clear: 'Cancel',
  clearFiltersAria: 'Clear selected filters',
  showFacetAria: 'Show facet',
  hideFacetAria: 'Hide facet',
  filterOptions: 'Filter options'
});
