/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */



define({
    dialogTitle: "Event action center",
    emptyListText: "Add new event",
    toolbarItemBack: "Back",
    actionPlan: "Action plan",
    addActionPlan: "Add action plan",
    columnEventName: "Event Name",
    columnSystemName: "System Name",
    columnActionPlan: "Action Plan",
    sourceLabel: "Source",
    rulesLabel: "Rules",
    runAs: "Run as",
    processMode: "Process mode",
    conjunctionAndLabel: "and",
    conjunctionOrLabel: "or",
    operatorEqualtoLabel: "equal to",
    operatorNotequaltoLabel: "not equal to",
    synchronouslyProcessLabel: "Synchronously",
    asynchronouslyProcessLabel: "Asynchronously",
    csObjLabel: "Content Server object",
    evtPropLabel: "Event property",
    prevActLabel: "Result from previous action",
    workspaceLabel: "Parent workspace",
    eventPropLabel: "Event property",
    reminderInitLabel: "Item initiating the event",
    selectSourceForEscalation: "Select source for escalation",
    labelExtendedECMVolume: "Extended ECM",
    saveLabel: "Save",
    cancelLabel: "Cancel",
    deleteActionPlanButton: "Delete",
    deleteActionPlanButtonAria: "Delete action plan",
    actionPlansGroup:"Action plans",
    backTitle: "Back",
    rulesTabLabel: "Rules",
    actionsTabLabel: "Actions",
    processModeTabLabel: "Process mode",
    rulesSetLegend: "Conditions",
    deleteActionPlanConfirmatonTitle: 'Delete action plan',
    deleteActionPlanConfirmatonText: 'Are you sure you want to delete {0}? ',
    newActionPlan: "New action plan",
    actionPlansListHeader: "Action plans",
    createLabel: "Create",
    closeLabel: "Close",
    genericWarningMsgOnDeletion: "Server Error: Unable to perform the action",
    warningMsgOnActionPlanNavigation: "All unsaved changes will be lost. Are you sure you want to continue?",
    actionPlanCreateError: "An item with the name '{0}' already exists.",
    actionPlanNavigationDialogTitle: "Unsaved changes",
    actionAttrParameterNameLabel: "Parameters",
    actionAttrParameterLabel: "Parameter",
    actionAttrSourceLabel: "Source",
    actionAttrValueLabel: "Value",
    actionPlanTitlePlaceholder: "Enter name",
    addToWareHouseFailure: "Failed to add to warehouse",
    requiredField: "This is a required field",
    conjunctionFieldLabel: "Expression",
    fromFieldLabel: "Event properties",
    toFieldLabel: "Value",
    operatorFieldLabel: "Operator",
    configureActionPlanText: "Add a name to start configuring action plan",
    delete:"Delete events",
    addToWareHouse:"Add to warehouse",
    rulesFieldPlaceholder: "Select value",
    Unclassified: "Unclassified",
    Any: "Any",
    Custom: "Custom",
    addEvents: "Add event",
    noReminderTypes : "No reminder types available for the reminder clients",
    reminderClientPlaceholder: "Select client",
    reminderTypePlaceholder: "Select type",
    eventInitDay: "Event initiation day",
    selectSourceForDueDate: "Select source for due date",
    days: "days",
    weeks: "weeks",
    months: "months",
    years: "years",
    selectSourceForAssignee: "Select source for assignee",
    roleLabel: "Role",
    categoryAttrLabel: "Category attribute",
    DependsOn: "Depends on previous action",
    DependsOnText: "Enable to execute current action after the completion of previous action",
    selectDifferentParameter: "Select a different parameter",
    centralWorkspaceTemplateIdPlaceholder: "Enter document template id",
    actions: "Actions",
    ContentServerUser: "Content Server user",
    fromPreviousAction: "From previous action",
    userInput: "User Input",
    Attribute: "Attribute",
    fromDesktop: "From desktop",
    fromShortcut: "Add Shortcut"
});