/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */

define({
  FilterCollapseTooltip: 'Hide filters',
  TreeBrowseCollapseTooltip: 'Hide navigation tree',
  EmailLinkSubject: 'I want to share the following links with you',
  EmailLinkDesktop: "Link for Desktop and Android",
  EmailAppleLinkFormat: "Link for iOS Mobile",
  CommandNameReserve: "Reserve",
  CommandVerbReserve: "reserve",
  ReservePageLeavingWarning: "If you leave the page now, pending items will not be reserved.",
  ReserveItemsNoneMessage: "No items reserved.",
  ReserveOneItemSuccessMessage: "1 item successfully reserved.",
  ReserveSomeItemsSuccessMessage: "{0} items successfully reserved.",
  ReserveManyItemsSuccessMessage: "{0} items successfully reserved.",
  ReserveOneItemFailMessage: "1 item failed to reserve.",
  ReserveSomeItemsFailMessage: "{0} items failed to reserve.",
  ReserveManyItemsFailMessage: "{0} items failed to reserve.",
  CommandNameUnreserve: "Unreserve",
  CommandVerbUnreserve: "unreserve",
  UnreservePageLeavingWarning: "If you leave the page now, pending items will not be unreserved.",
  UnreserveItemsNoneMessage: "No items unreserved.",
  UnreserveOneItemSuccessMessage: "1 item successfully unreserved.",
  UnreserveSomeItemsSuccessMessage: "{0} items successfully unreserved.",
  UnreserveManyItemsSuccessMessage: "{0} items successfully unreserved.",
  UnreserveOneItemFailMessage: "1 item failed to unreserve.",
  UnreserveSomeItemsFailMessage: "{0} items failed to unreserve.",
  UnreserveManyItemsFailMessage: "{0} items failed to unreserve.",
   CommandNameLock: "Lock",
   CommandVerbLock: "lock",
   LockPageLeavingWarning: "If you leave the page now, pending items will not be locked.",
   LockItemsNoneMessage: "No items locked.",
   LockOneItemSuccessMessage: "1 item successfully locked.",
   LockSomeItemsSuccessMessage: "{0} items successfully locked.",
   LockManyItemsSuccessMessage: "{0} items successfully locked.",
   LockOneItemFailMessage: "1 item failed to lock.",
   LockSomeItemsFailMessage: "{0} items failed to lock.",
   LockManyItemsFailMessage: "{0} items failed to lock.",
    CommandNameUnlock: "Unlock",
    CommandVerbUnlock: "unlock",
    UnlockPageLeavingWarning: "If you leave the page now, pending items will not be unlocked.",
    UnlockItemsNoneMessage: "No items unlocked.",
    UnlockOneItemSuccessMessage: "1 item successfully unlocked.",
    UnlockSomeItemsSuccessMessage: "{0} items successfully unlocked.",
    UnlockManyItemsSuccessMessage: "{0} items successfully unlocked.",
    UnlockOneItemFailMessage: "1 item failed to unlock.",
    UnlockSomeItemsFailMessage: "{0} items failed to unlock.",
    UnlockManyItemsFailMessage: "{0} items failed to unlock.",

});
