/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */

define({
  layoutTabTitle: 'Change page layout',
  widgetTabTitle: 'Add widget',
  expandTab: 'Expand tab',
  collapseTab: 'Collapse tab',
  noTitle: 'Title not available',
  goBackTooltip: 'Go back',
  templateMessage: 'Drag and Drop tile in position',
  changePageLayoutConfirmatonText: 'All your previously added and configured widgets will be lost!',
  proceedButton: 'Proceed',
  changeLayoutCancelButton: 'Cancel',
  FlowLayoutTitle: 'Flow layout',
  LcrLayoutTitle: 'Left center right layout',
  perspectiveSaveSuccess: 'Perspective has been updated successfully.',
  personalizationSaveSuccess: 'Changes saved successfully.',
  saveConfirmMsg: 'Please be aware this action will update all perspective overrides using this layout configuration. If you do not want this to happen, you should create a new perspective.',
  saveConfirmTitle: 'Save perspective',
  addWidget: 'Add widget',
  save: 'Save',
  saveAriaLabel: 'Save current layout',
  close: 'Close',
  cancelAriaLabel: 'Cancel the changes and exit edit mode',
  cancel: 'Cancel',
  reset: 'Reset',
  resetAriaLabel: 'Reset to default layout',
  resetConfirmMsg: 'Page will be reset to default page configured by the administrator.',
  configNotSupported: "This widget cannot be configured with edit page.",
  disableTitle: 'This widget can be added only once to the page',
  resetSuccessful: 'Reset to original page was successful.',
  tileLabel: 'Single Width',
  headerLabel: 'Double Width',
  fullpageLabel: 'Full Page',
  heroTileLabel: 'Full Width',
  RSPLayoutTitle: 'Right side panel layout',
  LSPLayoutTitle: 'Left side panel layout'
});
