/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */

define({
  columnSortAscendingTooltip: "{0} - Click to sort ascending",
  columnSortDescendingTooltip: "{0} - Click to sort descending",
  searchPlaceholder: '{0}',
  searchInputTooltip: 'Search {0}',
  searchByNamePlaceholder: 'Name',
  searchByNameAria: 'Search by name',
  searchIconTooltip: 'Search in {0}',
  searchClearIconTooltip: 'Clear',
  collapseSearch: 'Close search',
  collapseSearchAria: 'Clear all and close search',
  selectAll: 'Select all items',
  selectAllAria: 'Select all items',
  selectItem: 'Select {0}',
  selectItemAria: 'Select {0}. When selected an action bar of options can be reached per shift-tab',
  selectItemICanNotAria: 'Can not select {0}',
  selectedItemActionBarAria: 'Action bar of selected items',
  nameAria: '{0}',
  noUserFound: 'NO USERS FOUND',
  noResultsFound: 'No results found', //no results found in audit view searchbox typeahead dropdown.
  nameNoOpenAria: '{0}. Can not be opened.',
  NodeTableNoItems: "No item to display.",
  NodeTableNoSearchResult: "No results found.",
  NodeTableLoadingItems: "Loading...",
  NodeTableProcessingItems: "",
  NodeTablePageInfo: "Showing _START_ to _END_ of _TOTAL_ items",
  NodeTableEmptyPageInfo: "Showing 0 items",
  NodeTableFilteredPageInfo: "(filtered from _MAX_ total items)",
  NodeTablePageInfoSuffix: "",
  NodeTablePageThousandsSeparator: ",",
  NodeTablePagingFirst: "First",
  NodeTablePagingLast: "Last",
  NodeTablePagingPrevious: "Previous",
  NodeTablePagingNext: "Next",
  NodeTablePageSizeSelector: "Show _MENU_ items",
  NodeTablePageFilterLabel: "Filter by:",
  NodeTableSortedDescendingColumnAria: "{0} in descending order",
  NodeTableSortedAscendingColumnAria: "{0} in ascending order",
  NodeTableSortAscendingTooltip: "{0} - Click to sort ascending",
  NodeTableSortDescendingTooltip: "{0} - Click to sort descending",
  NodeTableIsUnsortedTooltip: "Unsorted",
  NodeTableSortAscendingButtonAria: "{0} - Sort ascending",
  NodeTableSortDescendingButtonAria: "{0} - Sort descending",
  MasterCompoundDocumentLabel: "Master",
  backButtonTooltip: 'Go back',
  typeAndNameAria: '{0} {1}', // MSWord document report12.doc
  tableApplicationAria: 'Table',
  selectionColumnTitle: 'Selected',
  descriptionColumnTitle: 'Description',
  toggleDetailsColumnTitle: 'Toggle details',
  cellNoTextAria: 'No text',
  noPermissions: "You don't have permissions to add items to this location.",
  promotedLabel: "Promoted",
  Bytes: 'Bytes',
  KiloBytes: 'KB',
  MegaBytes: 'MB',
  GigaBytes: 'GB',
  TeraBytes: 'TB',
  Items: '{0} Items',
  Item: '{0} Item',
  ZeroByte: '0 Byte',
  favorite: 'Favorite',
  reserved: 'Reserved'
});
