csui.define({
  toolbarButtonTitle: 'Izveidot / parakstīt konteineri',
  dialogTitle: 'Izveidot / parakstīt konteineri',
  submitLabel: 'Izveidot',
  submitSignLabel: 'Izveidot un parakstīt',
  docListHeader: 'Dokumenti',
  addNewVersion: 'Pievienot versiju',
  createNew: 'Uztaisīt jauno dokumentu',
  categoriesLabel: 'Kategorijas',
  categoryPlaceholder: 'Kategorijas nosaukums',
  containerName: 'Konteinera nosaukums',
  containerNamePlaceholder: 'Konteinera nosaukums',
  personCode: 'Personas kods',
  mobileNumbner: 'Mob. numurs',
  conCreated: 'Konteineris ir izveidots. Notiek parakstīšana...',
  signFinish: 'Konteineris ir veiksmīgi parakstīts.',
  conError: 'Notika kļūda. Mēģiniet vēlreiz.',
  msgPIN2Question: 'Statuss: parakstīšanas procedūra ir uzsākta. Ievadiet PIN2. Pārbaudes kods: ',
  msgContainerSignedDownload: 'Konteineris tika parakstīts: ',
  msgContainerCreatedDownload: 'Konteineris izveidots: ',
  download: 'lejuplādēt',
  msgErrorTryAgain: 'Statuss: ir notikusi kļūda. Mēģiniet vēlreiz.'
});
