define({
  toolbarButtonTitle: 'Izveidot / parakstīt konteineri',
  dialogTitle: 'Izveidot / parakstīt konteineri',
  submitLabel: 'Izveidot',
  submitSignLabel: 'Izveidot un parakstīt',
  submitShareLabel: 'Nosūtīt parakstīšanai',
  docListHeader: 'Dokumenti',
  addNewVersion: 'Pievienot versiju',
  createNew: 'Uztaisīt jauno dokumentu',
  categoriesLabel: 'Kategorijas',
  categoryPlaceholder: 'Kategorijas nosaukums',
  containerName: 'Konteinera nosaukums',
  containerNamePlaceholder: 'Konteinera nosaukums',
  personCode: 'Personas kods',
  mobileNumbner: 'Mob. numurs',
  conCreated: 'Konteineris ir izveidots. Notiek parakstīšana...',
  signFinish: 'Konteineris ir veiksmīgi parakstīts.',
  conError: 'Notika kļūda. Mēģiniet vēlreiz.',
  msgPIN2Question: 'Statuss: parakstīšanas procedūra ir uzsākta. Ievadiet PIN2. Pārbaudes kods: ',
  msgContainerSignedDownload: 'Konteineris tika parakstīts: ',
  msgContainerCreatedDownload: 'Konteineris izveidots: ',
  download: 'lejuplādēt',
  msgErrorTryAgain: 'Statuss: ir notikusi kļūda. Mēģiniet vēlreiz.',
  msgRedirect: 'Notiek redirekts parakstīšanas skatā',
  dialogTitleShareOrSign: 'Create container and share or sign',
  createContainerInformationModeSign: 'This action will create ASICE container from documents below and redirects you to signing view',
  createContainerInformationModeShare: 'This action will create ASICE container from documents below and redirects you to signing process initiation view',
  createContainerInformationModeShareOrSin: 'This action will create ASICE container from documents below and redirects you to signing view OR signing process initiation view depending on button pressed',
  createContainerAndRedirectSign: 'Creating container and redirecting to signing view...',
  /* BELOW ARE TECHNICAL FIELDS, DO NOT CHANGE WITHOUT CONSULTING */
  singleMode: 'single',
  multiMode: 'multi',
  modeSign: 'Sign',
  modeShare: 'Share',
  modeShareAndSign: 'Share And Sign',
  btnShareAndSignName: 'Sign or share as ASICE'  
});
